enhavo_translation:
    default_locale: '%locale%'
    translator:
        default_access: true
        access_control:
            - '#^(?!/admin/).*#'
    form:
        default_access: true
        access_control:
            - '#^/admin/.+#'
    translation_client:
        chain:
            clients:
                - Enhavo\Bundle\TranslationBundle\Client\DeeplTranslationClient
                - Enhavo\Bundle\TranslationBundle\Client\UrlTranslationClient

enhavo_app:
    roles:
        enhavo_translation_translation_memory_index:
            role: ROLE_ENHAVO_TRANSLATION_TRANSLATION_MEMORY_INDEX
            label: translation_memory.role.label.index
            translation_domain: EnhavoTranslationBundle
        enhavo_translation_translation_memory_update:
            role: ROLE_ENHAVO_TRANSLATION_TRANSLATION_MEMORY_UPDATE
            label: translation_memory.role.label.update
            translation_domain: EnhavoTranslationBundle
        enhavo_translation_translation_memory_delete:
            role: ROLE_ENHAVO_TRANSLATION_TRANSLATION_MEMORY_DELETE
            label: translation_memory.role.label.delete
            translation_domain: EnhavoTranslationBundle

enhavo_framework:
    locale_resolver: Enhavo\Bundle\TranslationBundle\Locale\LocalePathResolver

enhavo_doctrine_extension:
    metadata:
        Enhavo\Bundle\TranslationBundle\Entity\Translation:
            reference:
                object:
                    idField: refId
                    nameField: class

        Enhavo\Bundle\TranslationBundle\Entity\TranslationFile:
            reference:
                object:
                    idField: refId
                    nameField: class
                    cascade: ['persist']
